2025-01-14 20:23:49,429 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\Python Projects for University\lesson5\tests_12_4.py", line 21, in test_run
    run_2 = Runner(5, 10)
            ^^^^^^^^^^^^^
  File "C:\Users\User\Python Projects for University\lesson5\HMTest.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-14 20:23:49,432 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\Python Projects for University\lesson5\tests_12_4.py", line 10, in test_walk
    run_1 = Runner("Вася", -5)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Python Projects for University\lesson5\HMTest.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
